### ISSUE TITLE
Android: crash with borderless button on old device

### ISSUE THREAD

**Issue by Zycon42** [kmagiera/react-native-gesture-handler#122]
On android api 18 Huawei Y550-L01 crashes with following stacktrace

```
FATAL EXCEPTION: main
Process: eu.lmc.pzrb2c.beta, PID: 17359
android.content.res.Resources$NotFoundException: Resource ID #0x0
   at android.content.res.Resources.getValue(Resources.java:1170)
   at android.content.res.Resources.getDrawable(Resources.java:745)
   at com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager$ButtonViewGroup.createSelectableDrawable(RNGestureHandlerButtonViewManager.java:107)
   at com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager$ButtonViewGroup.updateBackground(RNGestureHandlerButtonViewManager.java:80)
   at com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager$ButtonViewGroup.access$000(RNGestureHandlerButtonViewManager.java:21)
   at com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager.onAfterUpdateTransaction(RNGestureHandlerButtonViewManager.java:173)
   at com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager.onAfterUpdateTransaction(RNGestureHandlerButtonViewManager.java:18)
   at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:35)
   at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:233)
   at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:153)
   at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1010)
   at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:981)
   at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
   at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:136)
   at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:107)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:766)
   at android.view.Choreographer.doCallbacks(Choreographer.java:581)
   at android.view.Choreographer.doFrame(Choreographer.java:550)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:754)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:136)
   at android.app.ActivityThread.main(ActivityThread.java:5333)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
   at dalvik.system.NativeStart.main(Native Method)
```

It's caused by using "selectableItemBackgroundBorderless" even on api < 21. I'm not an android expert but it seems to me that you should use "selectableItemBackground" always on this api.

**Comment by kmagiera** [comment]
Thanks @Zycon42 for reporting and investigating this issue. I merged your PR and release alpha.41
