### ISSUE TITLE
java.lang.IllegalArgumentException: Parent is null? View is no longer in the tree 

### ISSUE THREAD

**Issue by gaodeng** [kmagiera/react-native-gesture-handler#352]
```java
 --------- beginning of crash
11-25 16:42:09.093 24887-24887/fm.moon.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fm.moon.app, PID: 24887
    java.lang.IllegalArgumentException: Parent is null? View is no longer in the tree
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:331)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.extractCoordsForView(GestureHandlerOrchestrator.java:334)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandler(GestureHandlerOrchestrator.java:301)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.deliverEventToGestureHandlers(GestureHandlerOrchestrator.java:262)
        at com.swmansion.gesturehandler.GestureHandlerOrchestrator.onTouchEvent(GestureHandlerOrchestrator.java:102)
        at com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.dispatchTouchEvent(RNGestureHandlerRootHelper.java:121)
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent(RNGestureHandlerEnabledRootView.java:31)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5107)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4910)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4586)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4643)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7093)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7062)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7023)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7196)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7167)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7219)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:690)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by gre** [comment]
got the crash too

**Comment by ParhamZare** [comment]
I have the same issue, how fix this?

**Comment by osdnk** [comment]
Hi everyone, this issue appears to be resolved in a new release.

If you still face the problem, please let me know.
