### ISSUE TITLE
Example project broken on iOS

### ISSUE THREAD

**Issue by holden-caulfield** [kmagiera/react-native-gesture-handler#511]
Just pulled the latest on the repo and it looks like the Example project got broken.

Running `react-native run-ios`, the bundler crashes with the following output:

<pre>Failed to load bundle
(http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false) with error:
(Metro Bundler has encountered an internal error, please check your terminal 
error output for more details (null))</pre>

Bundler output says:

<pre>
error: bundling failed: Error: While trying to resolve module `@react-native-community/slider` 
from file `/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/combo/index.js`, 
the package `/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/@react-native-community/slider/package.json` was successfully found. 
However, this package itself specifies a `main` module field that could not be resolved (`/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/@react-native-community/slider/index`. 
Indeed, none of these files exist:

  * `/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/@react-native-community/slider/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/@react-native-community/slider/index/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/node-haste/DependencyGraph.js:273:16)
    at Object.resolve (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:391:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:388:18)
    at /Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:261:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/jpsaraceno/unbox-ws/react-native-gesture-handler/Example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)</pre>

Last commit log seems to be related:

`    Remove ViewPager and Slider in favor of exporting createNativeWrapper (#506)`

**Comment by JosephDunivan** [comment]
I looked in GestureHandler.js and its says `import Directions from './Directions';`, but no such function Directions exists in Directions.js. It sets `NativeModules` from react-native to `RNGestureHandlerModule `with method `.Direction` (which doesn't exist). Produces error `null is not and object (evaluating 'RNGestureModule.Direction')`

**Comment by jwheat** [comment]
I have this issue as well, just cloned the repo this morning (Mar 11).

**Comment by peterkuiper** [comment]
I had the same thing but after clearing the React Native cache (MacOS), the problem went away:

```
rm -rf $TMPDIR/metro-cache
```

NOTE: Always be careful when running `rm -rf`!

**Comment by osdnk** [comment]
@JosephDunivan  @jwheat  @peterkuiper  @holden-caulfield 2
Ok, can someone fix this Example? `Slider` should be taken from the community instead of RN. Would be grateful and will merge immediately.

**Comment by osdnk** [comment]
Also, @JosephDunivan, your issue is unrelated

**Comment by osdnk** [comment]
@peterkuiper 
Yes, I fixed it
